# Tensors
> is a mathematical object use to represent data with multiple dimensions

In [16]:
import numpy as np

In [17]:
# 0D - Scalar
a = np.array(4)

print('dimension of a: ',a.ndim)
# ndim provides us the dimension of ndimension(tensor) array

dimension of a:  0


In [18]:
# 1D - vector
a = np.array([1,2,3,4])

print('dimension of a: ',a.ndim)

# 'a' is a 1D tensor with 4 dimension
# the dimension of the vector 'a' are 4 
# whether as 'a' is a 1D tensor

# Axes : are directions they define how you move through your arrays dimensions.
# Number of Axes = Rank = Dimension Of Tensor

dimension of a:  1


In [19]:
# 2D - Matrix
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print('dimension of a: ',a.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimension of a:  2


# Note:
* When you add multiple scalars you get an vector
* Adding multiple vectors provides you matrices 
* Adding Multiple Matrices provides you 3D Tensors

In [20]:
# Rank = Number of axis = number of dimensions
# 2D Tensor = 2 Axes X,Y
# 3D Tensor = 3 Axes X,Y,Z

print(a)
# Shape - total items in any particular direction
print('Shape',a.shape)

# size of tensor  = shape(x,y,..) = x * y * ..
print('size of tensor ',a.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape (3, 3)
size of tensor  9


# Practical Requirements

In [21]:
# In Machine Learning we generally use 0D to 5D not

# 1D Tensors

In [22]:
# students dataset(1000) datapoints
# [cgpa,IQ,state,Placement]
# [9.2,132,MH,Yes(1)]
# [8.2,130,WB,No(0)]

# Assume our dataset have student from only 2 states 
# MH = 1,WB = 0 (Label Encoding)

# Now for above example
# [9.2,132,1] Its a 1D Tensor but its a 3D Vector

# Suppose You Got the Output of all the students
# The Result output itself is also an tensor of 1D
# [1,0,1,1,1,0,1]

# 2D Tensors

In [23]:
# [cgpa,IQ,state,Placement]
# [[9.2,132,MH,Yes(1)],
# [8.2,130,WB,No(0)]]

# In ML whenever you get data input data will be stored in Matrix(D)

# 3D Tensors

In [24]:
# 3D Tensors are more frequently used in domain of NLP

# Computer Doesnot Understand Text(String) we need to convert the text into number this is known as vectorization

# Text -> Number
# Hi Nitish [[1,0,0,0],[0,1,0,0]]
# Hi Rahul  [[1,0,0,0],[0,0,1,0]]
# Hi Ankit  [[1,0,0,0],[0,0,0,1]]

# In order to this we just do is number all unique words(Present in my corpus)
# Hi Nitish Rahul Ankit
# 1    0      0      0
# 0    1      0      0
# 0    0      1      0
# 0    0      0      1

# Time Series Data (Share Market Data)/(Medical Data)
# Day     Highest | Lowest  
# 1         -          -    
# 2

# Suppose we have it for 10 year (365,2)
# Here we have (10,365,2) 

# 4D Tensor

In [25]:
# 4D Tensors are mostly used in Computer CV
# RGB Image is 3D Tensor
# Collection of multiple Images is an 4D Tensor

# 5D Tensor

In [26]:
# Video are moving images 
# Videos are collection of frames

# Suppose we have a video of 60 sec 
# 30fps
# 480p resolution - 480 x 720
# 60 x 30 x 480 x 720 x 3(RGB)

# [[[480 x 720 x 3(RGB)],[],[]]
# [[480 x 720 x 3(RGB)],[],[]]]