> What is Numpy ?

NumPy is a Python library used for fast numerical computing, providing support for multi-dimensional arrays and high-performance mathematical operations.


At the core of the numpy package is the nd-array object.This encapsulates n-dimensional arrays of homogeneous datatypes

> Numpy Array Vs Python Sequences

* NumPy arrays store elements of the same data type, making them faster and memory-efficient. 
* Size of numpy array is fixed and changing size of nd array creates a new array and delete the original.
* Python sequences (lists, tuples) can store different data types but are slower for numerical operations.

> NumPy is written in C, and Python provides a wrapper over it, allowing us to use high-performance C code through simple Python syntax

In [1]:
# importing numpy 
import numpy as np

> Creating Numpy Arrays

* np.array() is used to create a NumPy array from a Python list or tuple, converting it into a homogeneous, efficient numerical array. 

In [ ]:
# np.array()
a = np.array([1,2,3,4])        # Homogeneous 
b = np.array([1,9.2,True,'s']) # Heterogeneous
print(type(a))
print(a,b)

# If a heterogeneous list is given to np.array(),
# NumPy upcasts all elements to a common data type, 
# usually converting everything to a string or object type.


<class 'numpy.ndarray'>
[1 2 3 4] ['1' '9.2' 'True' 's']


In [ ]:
# 2D and 3D
a = np.array([[1,2,5],[3,4,6]]) # 2D Matrix
print(a)

b = np.array([[[1,2],[3,4],[5,6]]]) #3D Tensor
print(b)

[[1 2 5]
 [3 4 6]]
[[[1 2]
  [3 4]
  [5 6]]]


In [ ]:
# dtype defines the data type of elements stored in a NumPy array, such as int, float, complex or bool.
# dtype is default int

a = np.array([1,2,3,4],dtype="float")
print(a)

[1. 2. 3. 4.]


In [ ]:
# np.arange() generates a NumPy array with evenly 
# spaced values within a given range, similar to Python’s range() 
# but returns an array.

a = np.arange(1,11)
print(a)

b= np.arange(1,101,2)
print(b)

# np.arange(start,end,step_size)


[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [45]:
# reshape() is used to change the shape of a NumPy array 
# without changing its data, as long as the total number 
# of elements remains the same.

a = np.array([1,2,3,4,5,6])
print(a.reshape(2,3))

print("----------------")

b = np.arange(1,11).reshape(5,2)
print(b)

print("----------------")

c = np.arange(16).reshape(2,2,2,2)
print(c)

[[1 2 3]
 [4 5 6]]
----------------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
----------------
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


> Array Initialization

In [ ]:
# np.ones() creates a NumPy array filled with 1s of a 
# specified shape and data type 
# input to the function is a tuple

a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# np.zeros() creates a NumPy array filled with 0s of a 
# specified shape and data type.

a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# np.random is a module used to generate random numbers and 
# random arrays for simulations, testing, and modeling.
# values are assign between 0 to 1 in random manner

a = np.random.random((3,3))
print(a)

[[0.6546081  0.29212265 0.3523448 ]
 [0.45343927 0.89601186 0.74219204]
 [0.94469557 0.03251762 0.24315923]]


In [ ]:
# np.linspace(range_start,range_end,total_values)
# generates a NumPy array of evenly spaced values between two limits, including both endpoints.

a= np.linspace(-10,10,10)
print(a)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [ ]:
# np.identity() creates an n × n identity matrix with 1s on the diagonal and 0s elsewhere.

a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


> Array Attributes

In [52]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
# ndim gives the number of dimensions of a NumPy array.

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)
 

1
2
3


In [60]:
# shape - shape gives the size of each dimension of a NumPy array as a tuple.

print(a1.shape) # 1d array with 10 columns
print(a2.shape) # 2d array with 3 rows and 4 columns
print(a3.shape) # 2 matrix with 2 x 2 dimensions

(10,)
(3, 4)
(2, 2, 2)


In [ ]:
# size → Total number of elements in the array.
print(a1.size)
print(a2.size)
print(a3.size)

print("---------------------------------------")
# itemsize → Memory (in bytes) of each element.
print(a1.itemsize) # int64 takes 8byte
print(a2.itemsize)
print(a3.itemsize)


10
12
8
---------------------------------------
8
8
8


# Changing Datatype

In [ ]:
# astype() Converts array elements to a specified data type.
# used to reduce the datatype of the column as required to save memory 

a3.astype(np.int32) 

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations

In [96]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)

print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
# Scalar Operation is an operation where a single value 
# (scalar) is applied to all elements of a NumPy array.

print("Before",a1)
# arithemetic operations  like +, -, *, / applied between a scalar and all array elements.
print("After")
b1 = a1 + 10
b1 = a1 - 10
b1 = a1 * 10
b1 = a1 / 10
print(b1) 

Before [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
After
[[0.  0.1 0.2 0.3]
 [0.4 0.5 0.6 0.7]
 [0.8 0.9 1.  1.1]]


In [ ]:
# Relational it operates item by item Comparisons like 
# >, <, == applied between a scalar and all array elements, 
# returning a boolean array.

a2 > 10 

a2 < 10

a2 > 15

a2 == 16

a2 != 16

array([[ True,  True,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [101]:
# Vector operations Element-wise operations between two arrays of the 
# same shape, like addition, subtraction, multiplication, or division.

# Arithemetic Vector Operation
a1 + a2
a1 - a2 
a1 * a2
a1 / a2
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

> Array Function

In [113]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)

print(a1)

[[43. 94. 21.]
 [14. 50. 57.]
 [17. 88. 96.]]


In [ ]:
# max/min/sum/prod
# max → Largest element in the array
# min → Smallest element in the array
# sum → Sum of all elements
# prod → Product of all elements

maximum = np.max(a1)        
minimum = np.min(a1)
summation = np.sum(a1)
product_sum = np.prod(a1)

486397491148800.0


In [120]:
# axis → Specifies the dimension along which an operation is performed in a NumPy array.

maximum = np.max(a1,axis=0) # returns maximum value present in the row/column, if axis = 1 (row) / axis = 0(column)
print(maximum)

minimum = np.min(a1,axis = 1)
print(minimum)


[43. 94. 96.]
[21. 14. 17.]


In [ ]:
# mean/median/std/var
# mean → Average of elements
# median → Middle value
# std → Standard deviation (spread of data)
# var → Variance (square of std)

np.mean(a1)
np.median(a1)
np.std(a1)
np.var(a1)

np.float64(968.8888888888889)

In [126]:
# trigonometric functions
np.sin(a1)

array([[-0.83177474, -0.24525199,  0.83665564],
       [ 0.99060736, -0.26237485,  0.43616476],
       [-0.96139749,  0.0353983 ,  0.98358775]])

In [ ]:
# dot product 
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

# dot() Computes the dot product of two arrays (sum of element-wise products).

prod = np.dot(a2,a3)
print(prod)

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [136]:
# log and exponents

# np.log() → Natural logarithm of elements
logvalue = np.log(a2)
print(logvalue)

print("------------------------------------------------")

# np.exp() → Exponential (e^x) of elements
expval = np.exp(a2)
print(expval)


[[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]
 [2.07944154 2.19722458 2.30258509 2.39789527]]
------------------------------------------------
[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]


C:\Users\parth\AppData\Local\Temp\ipykernel_4600\2048484887.py:4: RuntimeWarning: divide by zero encountered in log
  logvalue = np.log(a2)


In [187]:
# round/floor/ceil
# np.round() → Rounds elements to nearest integer
print(np.round(np.random.random((3,4))*100))

print("---------------------------------------------")

# np.floor() → Rounds down to nearest integer
print(np.floor(np.random.random((3,4))*100))

print("---------------------------------------------")
# np.ceil() → Rounds up to nearest integer
print(np.ceil(np.random.random((3,4))*100))


[[59. 53. 90. 58.]
 [22. 40. 90. 45.]
 [81. 29. 62. 21.]]
---------------------------------------------
[[39. 22. 52. 83.]
 [ 4. 75. 25. 25.]
 [82. 37. 65. 38.]]
---------------------------------------------
[[12. 55.  8.  5.]
 [60. 25. 57. 57.]
 [98. 98. 68. 53.]]


# Indexing 

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
# indexing is similar to that of lists

# 1D indexing
a1[-1]
a1[1:6:2]

array([1, 3, 5])

In [ ]:
# 2D indexing
print(a2)
a2[1,2]      # a2[row,col]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


np.int64(6)

In [202]:
print(a3)
# 3D indexing
a3[1,0,1]    # a3[matrix,row,col]
a3[0,1,1]
a3[0,0,0]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


np.int64(0)

# Slicing

In [206]:
a1 = np.arange(1,10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
# Similar to List in 1D
print(a1)
# slice 2,3,4,5,6
a1[1:6]

[1 2 3 4 5 6 7 8 9]


array([2, 3, 4, 5, 6])

In [239]:
# 2D 
print(a2)

a2[0,3]    # a[row,col+1]
a2[0,:]
a2[:,2]

a2[1:3,1:3]

a2[::2,::3]

a2[::2,1::2]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 1,  3],
       [ 9, 11]])

In [263]:
# 3D 
a3 = np.arange(27).reshape(3,3,3)
print(a3)

print("----------------------------")

a3[0,1,:]   # a[matrix,row,column]

a3[1,:,1]
a3[2,1:,1:]
a3[0::2,0::3,0::2]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
----------------------------


array([[[ 0,  2]],

       [[18, 20]]])

# Iterating

In [267]:
a1

for i in a1:
    print(i)

1
2
3
4
5
6
7
8
9


In [268]:
a2

for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [269]:
a3

for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


> nditer() is used to iterate over each element of a NumPy array efficiently, regardless of its dimensions.

In [273]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


# Reshaping
> reshape() Changes the shape of an array without changing data

> Transpose() Swaps rows and columns of an array

> ravel() Converts a multi-dimensional array into a 1D array

In [ ]:
print(a2)

print("-----------------------")
# reshape
b1 = a2.reshape(4,3)
print(b1)

print("-----------------------")
# transpose
b2 = a2.transpose() # Swaps rows and columns
# b2 = a2.T           short hand
print(b2)

print("-----------------------")
# ravel
b3 = a2.ravel()
print(b3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
-----------------------
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
-----------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]


# Stacking 
> Combining multiple NumPy arrays along a new or existing axis (row-wise or column-wise).

In [292]:
# Horizontally 
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

b1 = np.hstack((a1,a2,a2))
print(b1)


[[ 0  1  2  3 12 13 14 15 12 13 14 15]
 [ 4  5  6  7 16 17 18 19 16 17 18 19]
 [ 8  9 10 11 20 21 22 23 20 21 22 23]]


In [293]:
# Vertically
b2 = np.vstack((a1,a2,a1))
print(b2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# Splitting 
> Dividing a Numpy array into smaller sub-arrays along a specified axis.

In [ ]:
# Horizontal Split
print(b1)
print("-----------------------")
x1,x2,x3 = np.hsplit(b1,3)

print(x1)
print("-----------------------")
print(x2)
print("-----------------------")
print(x3)

[[ 0  1  2  3 12 13 14 15 12 13 14 15]
 [ 4  5  6  7 16 17 18 19 16 17 18 19]
 [ 8  9 10 11 20 21 22 23 20 21 22 23]]
-----------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------------------
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
-----------------------
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [307]:
# Vertical Split
print(b2)
print("-----------------------")
x1,x2,x3 = np.vsplit(b2,3)

print(x1)
print("-----------------------")
print(x2)
print("-----------------------")
print(x3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------------------
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
-----------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
